version: '3.8'

services:
  exp_tr_postgres:
    container_name: expenses_tracker_container
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - exp_tr_postgres:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432

volumes:
  exp_tr_postgres:
